config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :instruments
  resources :users

  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

###
# ApplicationRecord Class
#
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
# frozen_string_literal: true

###
# Instrument Class
#
class Instrument < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true

  def to_s
    title
  end

  has_rich_text :description
end

app/models/user.rb
# frozen_string_literal: true

###
# User class
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

###
# ActionController class
#
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

###
# HomeController Class
#
class HomeController < ApplicationController
  def index; end
end

app/controllers/instruments_controller.rb
# frozen_string_literal: true

###
# InstrumentsController Class
#
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[show edit update destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = if params[:title]
                     # case-insensitive search
                     Instrument.where('title ILIKE ?', "%#{params[:title]}%")
                   else
                     Instrument.all
                   end
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show; end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit; end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: t('Instrument was successfully created.') }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: t('Instrument was successfully updated.') }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: t('Instrument was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_instrument
    @instrument = Instrument.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def instrument_params
    params.require(:instrument).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

###
# UsersController Class
#
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = if params[:email]
               User.where('email ILIKE ?', "%#{params[:email]}%")
             else
               User.all
             end
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('User was successfully created.') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('User was successfully updated.') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('User was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

###
# ApplicationHelper Module
#
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

##
# HomeHelper Module
#
module HomeHelper
end

app/helpers/instruments_helper.rb
# frozen_string_literal: true

###
# InstrumentsHelper Module
#
module InstrumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/My-----users/index.html.haml
%h1
  Users:
  = @users.count

= link_to new_user_registration_path do
  .fa.fa-user-plus.text-dark
  %span.text-dark
    Add new user...

%table.table
  %thead
    %tr
      %th Email
      %th.row-size Type
      %th Created
      %th.row-size
      %th.row-size
      %th.row-size

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td
        %td= "#{time_ago_in_words(user.created_at)}" + ' ' + 'ago'
        %td
          = link_to user do
            .btn.btn-success
              .fa.fa-eye
              Show
        %td
          = link_to edit_user_registration_path(user) do
            .btn.btn-warning
              .fa.fa-edit
              Edit
        %td
          = link_to user, method: :delete, data: { confirm: 'Are you sure?' }  do
            .btn.btn-danger
              .fa.fa-trash-alt
              Delete

app/views/My-----users/show.html.haml
%p#notice= notice

%p
  %b email:
  = @user.email
%p
  %b Creation date:
  = @user.created_at

= link_to t('Edit'), edit_user_registration_path(@user)
\|
= link_to t('Back'), users_path

app/views/active_storage/blobs/_blob.html.haml
- preview? = blob.representable? ? "preview" : "file"
- file? = blob.filename.extension
%figure{ class: "attachment attachment--#{preview?} attachment--#{file?}" }
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [800, 600] : [1024, 768])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/home/index.html.haml
Index

app/views/instruments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@instrument) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description

  .form-actions
    = f.button :submit

app/views/instruments/edit.html.haml
%h1 Editing instrument

= render 'form'

= link_to 'Show', @instrument
\|
= link_to 'Back', instruments_path

app/views/layouts/_header.html.haml
- if current_user
  %nav.navbar.navbar-expand-lg.pb-0.navbar-light.bg-light
    %a.navbar-brand{ href: '/' }
      .fa.fa-home
        Eclisse MSM
    %button.navbar-toggler{ 'aria-controls' => 'navbar-supported-content',
                            'aria-expanded' => 'false',
                            'aria-label' => 'Toggle navigation',
                            'data-target' => '#navbar-supported-content',
                            'data-toggle' => 'collapse',
                            type: 'button' }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-supported-content
      %ul.nav.nav-tabs.mr-auto.border-bottom-0
        %li.nav-item
          %a.nav-link.border-bottom-0.border.border-warning.text-dark{ href: users_path,
            class: "#{'active font-weight-bold bg-warning txt-white' if current_page?(users_path)}" }
            .fa.fa-users
            Users
        %li.nav-item
          %a.nav-link.border-bottom-0.border.border-info.text-dark{ href: instruments_path,
            class: "#{'active font-weight-bold bg-info txt-white' if current_page?(instruments_path)}" }
            .fa.fa-guitar
            Instruments
            .fa.fa-drum
      %form.form-inline.mx-2.my-lg-0
        = form_tag(root_path, method: :get) do
          .input-group
            = text_field_tag :title,
              params[:title],
              autocomplete: 'off',
              placeholder: 'Search',
              class: 'form-control'
            %span.input-group-append
              %button.btn.btn-outline-secondary.btn-sm{ type: 'submit' }
                %span.fa.fa-search{ 'aria-hidden' => 'true' }
      .dropdown.mx-2
        %a.fa.fa-user-circle.text-success.my-account#dropdown-menu-button{ 'aria-expanded' => 'false',
                                                                           'aria-haspopup' => 'true',
                                                                           'data-toggle' => 'dropdown',
                                                                           type: 'button' }
        .dropdown-menu.dropdown-menu-right{ 'aria-labelledby' => 'dropdownMenuButton' }
          .dropdown-item.disabled
            = current_user.email
          .dropdown-item
            = link_to edit_user_registration_path do
              .fa.fa-users-cog
              Account settings
          .dropdown-item
            = link_to destroy_user_session_path, method: :delete do
              .fa.fa-sign-out-alt.text-danger
              %span.text-danger
                Sign out
- else
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .navbar-brand
      .fa.fa-home
        Eclisse MSM
    %button.navbar-toggler{ 'aria-controls' => 'navbar-supported-content-login',
                            'aria-expanded' => 'false',
                            'aria-label' => 'Toggle navigation',
                            'data-target' => '#navbar-supported-content-login',
                            'data-toggle' => 'collapse',
                            type: 'button' }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-supported-content-login
      %ul.nav.nav-tabs.mr-auto
        %li.nav-item
      %form.form-inline.mx-2.my-lg-0
        %button.btn.btn-outline-secondary.mr-sm-2{ type: 'button' }
          = link_to new_user_registration_path do
            .fa.fa-user-plus.text-dark
            %span.text-dark
              Sign up
        %button.btn.btn-outline-secondary{ type: 'button' }
          = link_to new_user_session_path do
            .fa.fa-sign-in-alt.text-dark
            %span.text-dark
              Log in

app/views/layouts/_messages.html.haml
- flash.each do |name, message|
  - if message.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} fade show", role: 'alert' }
      %button.close{ 'aria-hidden' => 'true',
                      'aria-label' => 'Close',
                      'data-dismiss' => 'alert',
                      :type => 'button' } &times;
      = content_tag(:div, message, id: "flash_#{name}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Eclisse MSM
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    %div{ class: "container#{'-fluid' if current_user}#{' text-center' unless current_user}" }
      = render 'layouts/messages'
      = yield

app/views/users/_form.html.haml
-# frozen_string_literal: true

= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing users

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1
  Instruments:
  = @instruments.count

%table.table
  %thead
    %tr
      %th Instrument
      %th Description
      %th.row-size
      %th.row-size
      %th.row-size

  %tbody
    - @instruments.each do |instrument|
      %tr
        %td= instrument.title
        %td= instrument.description
        %td= link_to '<span class="fa fa-eye"> Show'.html_safe,
              instrument,
              :class => 'btn btn-success'
        %td= link_to '<span class="fa fa-edit"> Edit'.html_safe,
              edit_instrument_path(instrument),
              :class => 'btn btn-warning'
        %td= link_to '<span class="fa fa-trash-alt"> Delete'.html_safe,
              instrument,
              method: :delete,
              data: { confirm: 'Are you sure?' },
              :class => 'btn btn-danger'

= link_to '<span class="fa fa-plus-circle"> Add new instrument...'.html_safe,
  new_instrument_path

app/views/users/new.html.haml
%h1 New instrument

= render 'form'

= link_to 'Back', instruments_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @instrument.title
%p
  %b Description:
  = @instrument.description

= link_to 'Edit', edit_instrument_path(@instrument)
\|
= link_to 'Back', instruments_path